### ISSUE TITLE
Apparent Wind Angle

### ISSUE THREAD

**Issue by Nereus32** [canne/dashboard_tactics_pi#72] opened 2019-08-23 19:19 UTC
Something odd...

Apparent wind angle is showing as a reciprocal of the actual apparent wind angle on MacOS Mojave, Ov5.01 and Dashboard_Tactics .3.05 & .40 (just upgraded). See screen shots. First is DBTactics showing the correct wind on compass rose and the reciprocal wind on the apparent wind gauge. I removed DBTactics and reenabled Dashboard, and all is fine (see screen shot 2). Also a screen shot of my iPhone showing the correct wind angle on the SeatalkNG network, so the data is right - matches the ST60 gauge on the boat. Is there a setting I set that has reversed the wind angle on the Apparent Wind Gauge in O5.01?

Steve

![Screen Shot 2019-08-23 at 11 51 45 AM](https://user-images.githubusercontent.com/39605258/63617853-6830a080-c59f-11e9-810b-ea4298a61008.png)
![Screen Shot 2019-08-23 at 12 07 26 PM](https://user-images.githubusercontent.com/39605258/63617860-6bc42780-c59f-11e9-802e-a50d1a995c88.png)
![IMG_36406C16E62D-1](https://user-images.githubusercontent.com/39605258/63617869-72eb3580-c59f-11e9-9520-5ec860b602f9.jpeg)

**Comment by canne** [comment] 2019-08-23 20:10
Hi, thank you for reporting and sorry for the bug I "introduced" in the "normal" (single needle) dial around v3.5. This has been reported already in bug #71 and fixed. There is an explanation how to fix this on your own (presuming you make your own build) in this [forum post](http://www.cruisersforum.com/forums/f134/tactics-plugin-166909-52.html#post2957880) (subject #1 addressed at the end of the post). Or you can take [this commit](https://github.com/canne/dashboard_tactics_pi/commit/9c37709e934ef47932d7833df83f3f9cf502bf4d) entirely, as it is. You can see from the continuous integration that it builds on osx. 

Note that I am developing in branch right now, awaiting also for a new feature from Tactics before I make a new release, which is a bit time consuming. It will take a couple of weeks, I reckon.

Sorry for the inconvenience, I have improved the regression testing of dials to make sure that this will not occur again.

**Comment by canne** [comment] 2019-08-23 20:12
Closing as duplicate of bug #71 .

**Closed by canne** 2019-08-23 20:12 UTC
Labels: duplicate
